<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-09-13T17:12:27</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>172e466f-b037-44da-a2e3-4f94ce05bb6e</testSuiteGuid>
   <testCaseLink>
      <guid>61fbdf0d-69b2-44b6-9ae1-af397076bb6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginFunctionalityTests/FB_LoginTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90a1366e-6c80-4d5b-b544-32aee360d53f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a83b31f0-5500-43f4-b108-6414e148d5fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0603a5d2-7818-463e-9d61-925059d8d76d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginFunctionalityTests/LoginTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de73f16a-649d-464e-a523-89366e7012d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcbbd2ef-e988-4722-b609-7fd30e5e7794</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
